#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
### END INIT INFO

#Cameras
camera1='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera2='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera3='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera4='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'

# ------------- Use extreme caution when editing below this line ---------------------------
#Screen Control
case "$1" in
  cam1)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -dmS stream2 sh -c 'omxplayer --win "0 0 800 480" '$camera1' -b --live; exec bash'
    echo 130 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 1s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    /home/pi/cgi-bin/./2tone
    ;;
  cam2)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -dmS stream3 sh -c 'omxplayer --win "0 0 800 480" '$camera2' -b --live; exec bash'
    echo 130 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 1s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    /home/pi/cgi-bin/./2tone   
    ;;
  cam3)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -dmS stream4 sh -c 'omxplayer --win "0 0 800 480" '$camera3' -b --live; exec bash'
    echo 130 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 1s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    /home/pi/cgi-bin/./2tone
    ;;
  cam4)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -dmS stream5 sh -c 'omxplayer --win "0 0 800 480" '$camera4' -b --live; exec bash'
    echo 130 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 1s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    /home/pi/cgi-bin/./2tone   
    ;;
  camStop)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -X -S stream2 quit
    screen -X -S stream3 quit
    screen -X -S stream4 quit
    screen -X -S stream5 quit
    echo 50 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 1s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    ;;
  MMstart)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    cd /home/pi/MagicMirror
    screen -dmS stream1 sh -c 'DISPLAY=:0 npm start; exec bash'
    echo 50 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 6s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    ;;
  PFstart)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -dmS stream1 sh -c 'DISPLAY=:0.0 XAUTHORITY=/home/pi/.Xauthority /usr/bin/feh -q -p -z -Z -F -R  60 -Y -D 60 /home/pi/Pictures; exec bash'
    echo 50 | sudo tee /sys/class/backlight/rpi_backlight/brightness
    sleep 6s
    echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    ;;
  stop)
    echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
    screen -X -S stream1 quit
    ;;


*)
exit 1
;;

esac
