#!/bin/bash

sleep 30s
echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
screen -X -S stream2 quit
screen -X -S stream3 quit
screen -X -S stream4 quit
screen -X -S stream5 quit
echo 50 | sudo tee /sys/class/backlight/rpi_backlight/brightness
sleep 1s
echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
