#!/bin/bash

echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
sudo killall omxplayer.bin
screen -X -S stream1 quit
screen -dmS stream1 sh -c 'DISPLAY=:0.0 XAUTHORITY=/home/pi/.Xauthority /usr/bin/feh -q -p -z -F -R  60 -Y -D 60.0 /home/pi/Pictures; exec bash'
echo 50 | sudo tee /sys/class/backlight/rpi_backlight/brightness
sleep 2s
echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
